
title: A Blog for Things
email: andrew@andrewbooth.xys
description: A Blog for Things
baseurl: /blog
url: https://andrewbooth.xyz
twitter_username: broothie
github_username:  broothie

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
